/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author DHAFFA
 */
public class DetailNota_2 extends javax.swing.JFrame {
    private String selectedNoNota; 
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DetailNota_2.class.getName());
    private int loggedInUserId;
    
    /**
     * Creates new form DetailNota_2
     */
    // Ubah constructor bawaan agar menerima parameter noNota
    
    public DetailNota_2(String noNota, int userId) {
        initComponents();
        this.selectedNoNota = noNota; 
        this.loggedInUserId = userId; 
        
        this.setSize(600, 490); 
        this.setLocationRelativeTo(null);
        jTable1.setRowHeight(40);
        this.setResizable(false);
        loadDetailData();
    }
    public DetailNota_2(String noNota) {
    initComponents();
    this.selectedNoNota = noNota; 
    this.setResizable(false);
    this.setSize(600, 490); 
    this.setLocationRelativeTo(null);
    
    
   
    jTable1.setRowHeight(40);
    
    loadDetailData();
    }   
    public DetailNota_2() {
        
        this.setSize(600, 490); 
        this.setResizable(false);
        initComponents();    
        jTable1.setRowHeight(40);
        this.setLocationRelativeTo(null);
    }
    private void loadDetailData() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); 

    String url = "jdbc:sqlserver://localhost:1433;databaseName=DbNotaku;encrypt=true;trustServerCertificate=true;";
    String userDb = "Test1";
    String passDb = "123"; 

    String sqlNota = "SELECT no_nota, nama_toko FROM Nota WHERE no_nota = ?";
    
    String sqlDetail = "SELECT jumlah, nama_barang, harga_satuan, total_harga FROM DetailNota WHERE no_nota = ?";

    try (Connection conn = DriverManager.getConnection(url, userDb, passDb)) {
        
        try (PreparedStatement psNota = conn.prepareStatement(sqlNota)) {
            psNota.setString(1, selectedNoNota);
            ResultSet rsNota = psNota.executeQuery();
            if (rsNota.next()) {
                
                NoNotaLabel.setText(rsNota.getString("no_nota"));
                NamaTokoLabel.setText(rsNota.getString("nama_toko"));
            }
        }

        try (PreparedStatement psDetail = conn.prepareStatement(sqlDetail)) {
            psDetail.setString(1, selectedNoNota);
            ResultSet rsDetail = psDetail.executeQuery();
            
            int grandTotal = 0;
            
            while (rsDetail.next()) {
            int jumlah = rsDetail.getInt("jumlah"); 
            String namaBarang = rsDetail.getString("nama_barang");
            int hargaSatuan = rsDetail.getInt("harga_satuan");
            int subtotal = rsDetail.getInt("total_harga"); 
            
            grandTotal += subtotal; 
            
            model.addRow(new Object[]{jumlah, namaBarang, hargaSatuan, subtotal});
        }
            
            TotalField.setText(String.valueOf(grandTotal));
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat detail nota: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CloseButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pembatasLabel = new javax.swing.JLabel();
        TotalField = new javax.swing.JTextField();
        NoNotaLabel = new javax.swing.JLabel();
        TotalLabel = new javax.swing.JLabel();
        NamaTokoLabel = new javax.swing.JLabel();
        UpdateButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CloseButton.setBackground(new java.awt.Color(255, 87, 87));
        CloseButton.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        CloseButton.setText("KEMBALI");
        CloseButton.addActionListener(this::CloseButtonActionPerformed);
        getContentPane().add(CloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 19, -1, 30));

        jTable1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "BANYAK", "NAMA BARANG", "HARGA SATUAN", "SUBTOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Long.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 540, 320));

        pembatasLabel.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 14)); // NOI18N
        pembatasLabel.setText("/");
        getContentPane().add(pembatasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 24, 10, -1));

        TotalField.setEditable(false);
        TotalField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TotalField.addActionListener(this::TotalFieldActionPerformed);
        getContentPane().add(TotalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 150, -1));

        NoNotaLabel.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        NoNotaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NoNotaLabel.setText("NOMER NOTA");
        NoNotaLabel.setToolTipText("");
        getContentPane().add(NoNotaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 26, 150, -1));

        TotalLabel.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20)); // NOI18N
        TotalLabel.setText("TOTAL");
        getContentPane().add(TotalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 403, 60, -1));

        NamaTokoLabel.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        NamaTokoLabel.setText("NAMA TOKO");
        getContentPane().add(NamaTokoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 26, 170, -1));

        UpdateButton.setBackground(new java.awt.Color(255, 222, 89));
        UpdateButton.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        UpdateButton.setText("UBAH NOTA");
        UpdateButton.addActionListener(this::UpdateButtonActionPerformed);
        getContentPane().add(UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BackgroundDetailNota.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        String noNotaAktif = NoNotaLabel.getText(); 
    
        UpdateNota_3 halamanUpdate = new UpdateNota_3(noNotaAktif, this.loggedInUserId);
        halamanUpdate.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        ListNota_1 listHalaman = new ListNota_1(this.loggedInUserId); 
        listHalaman.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void TotalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DetailNota_2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseButton;
    private javax.swing.JLabel NamaTokoLabel;
    private javax.swing.JLabel NoNotaLabel;
    private javax.swing.JTextField TotalField;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel background;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel pembatasLabel;
    // End of variables declaration//GEN-END:variables
}
