/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *\
 *
 * @author DHAFFA
 */
public class ListNota_1 extends javax.swing.JFrame {
    public ListNota_1() {
    initComponents();
    loadData(); 
    this.setSize(600, 490);
    this.setLocationRelativeTo(null);
   
}   
    private void loadData() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); 

    String url = "jdbc:sqlserver://localhost:1433;databaseName=DbNotaku;encrypt=true;trustServerCertificate=true;";
    String user = "Test1"; 
    String password = "123"; 

    String query = "SELECT * FROM Nota";

    try (Connection conn = DriverManager.getConnection(url, user, password);
         Statement stmt = conn.createStatement();
         ResultSet rs = stmt.executeQuery(query)) {

        while (rs.next()) {
            String noNota = rs.getString("no_nota");
            String namaToko = rs.getString("nama_toko");
            String alamat = rs.getString("alamat");
            String tanggal = rs.getString("tanggal");

            model.addRow(new Object[]{noNota, namaToko, alamat, tanggal});
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal memuatkan data: " + e.getMessage(), "Ralat", JOptionPane.ERROR_MESSAGE);
    }
}
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {                                          

    UpdateNota_3 halamanTambah = new UpdateNota_3();
    halamanTambah.setVisible(true);

    this.dispose(); 
}
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {                                         
  
    int selectedRow = jTable1.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Sila pilih baris nota yang ingin dihapus terlebih dahulu!");
        return;
    }

    String noNota = jTable1.getValueAt(selectedRow, 0).toString();

    int confirm = JOptionPane.showConfirmDialog(this, 
            "Adakah anda pasti ingin menghapus Nota " + noNota + "?\nSemua detail barang di dalamnya juga akan terhapus.", 
            "Pengesahan Hapus", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        String url = "jdbc:sqlserver://localhost:1433;databaseName=DbNotaku;encrypt=true;trustServerCertificate=true;";
        String user = "sa";
        String password = "password_anda"; 
        
        String sql = "DELETE FROM Nota WHERE no_nota = ?";

        try (Connection conn = DriverManager.getConnection(url, user, password);
             PreparedStatement ps = conn.prepareStatement(sql)) {
            
            ps.setString(1, noNota);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Nota Berhasil Dihapus!");
            
            loadData(); 
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus nota: " + e.getMessage(), "Ralat", JOptionPane.ERROR_MESSAGE);
        }
    }
    
}
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListNota_1.class.getName());

    /**
     * Creates new form ListNota
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 457));
        setMinimumSize(new java.awt.Dimension(600, 457));
        setPreferredSize(new java.awt.Dimension(600, 457));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 220, 77));
        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("TAMBAH NOTA BARU");
        jButton1.setToolTipText("");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 150, 30));

        jButton3.setBackground(new java.awt.Color(255, 87, 87));
        jButton3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        jButton3.setText("HAPUS NOTA");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 120, 30));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"asd", "asd", "as", "asd"},
                {"asdadsa", "dasdasd", "asd", null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No Nota", "Nama Toko", "Alamat", "Tanggal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 540, 320));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BackGroundNotaFix.png"))); // NOI18N
        Background.setPreferredSize(new java.awt.Dimension(600, 457));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ListNota_1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
