/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author DHAFFA
 */
public class Login_0 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login_0.class.getName());

    /**
     * Creates new form Login_0
     */
    public Login_0() {
        
        initComponents();
        this.setResizable(false);
        lblpasswordKonf.setVisible(false); 
        TFpasswordKonf.setVisible(false); 
        JudulBuatAkun.setText("LOGIN AKUN"); 
        SIGNUPBTN.setText("SIGN-IN");
        this.setLocationRelativeTo(null);
        this.setSize(600, 490);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsername = new javax.swing.JLabel();
        JudulBuatAkun = new javax.swing.JLabel();
        TFpassword = new javax.swing.JTextField();
        lblpasswordKonf = new javax.swing.JLabel();
        TFpasswordKonf = new javax.swing.JTextField();
        lblpassword = new javax.swing.JLabel();
        TFusername = new javax.swing.JTextField();
        SIGNUPBTN = new javax.swing.JButton();
        ButtonAkunLama = new javax.swing.JButton();
        ButtonAkunBaru = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(171, 197, 253));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsername.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        lblUsername.setText("Username");
        getContentPane().add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        JudulBuatAkun.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        JudulBuatAkun.setText("BUAT AKUN");
        getContentPane().add(JudulBuatAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 90, 30));

        TFpassword.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        TFpassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, java.awt.Color.lightGray));
        TFpassword.addActionListener(this::TFpasswordActionPerformed);
        getContentPane().add(TFpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 200, 20));

        lblpasswordKonf.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        lblpasswordKonf.setText("Verfikasi Password");
        getContentPane().add(lblpasswordKonf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        TFpasswordKonf.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        TFpasswordKonf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, java.awt.Color.lightGray));
        TFpasswordKonf.addActionListener(this::TFpasswordKonfActionPerformed);
        getContentPane().add(TFpasswordKonf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 200, 20));

        lblpassword.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        lblpassword.setText("Password");
        getContentPane().add(lblpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        TFusername.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        TFusername.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, java.awt.Color.lightGray));
        TFusername.addActionListener(this::TFusernameActionPerformed);
        getContentPane().add(TFusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 200, 20));

        SIGNUPBTN.setBackground(new java.awt.Color(138, 221, 202));
        SIGNUPBTN.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        SIGNUPBTN.setText("SIGN-UP");
        SIGNUPBTN.addActionListener(this::SIGNUPBTNActionPerformed);
        getContentPane().add(SIGNUPBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 140, 30));

        ButtonAkunLama.setBackground(new java.awt.Color(138, 221, 202));
        ButtonAkunLama.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        ButtonAkunLama.setText("MASUK AKUN LAMA");
        ButtonAkunLama.addActionListener(this::ButtonAkunLamaActionPerformed);
        getContentPane().add(ButtonAkunLama, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 140, 30));

        ButtonAkunBaru.setBackground(new java.awt.Color(255, 222, 89));
        ButtonAkunBaru.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        ButtonAkunBaru.setText("BUAT AKUN BARU");
        ButtonAkunBaru.addActionListener(this::ButtonAkunBaruActionPerformed);
        getContentPane().add(ButtonAkunBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 130, 30));

        Background.setBackground(new java.awt.Color(171, 197, 253));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BackgroundLogin.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFusernameActionPerformed

    private void TFpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFpasswordActionPerformed

    private void TFpasswordKonfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFpasswordKonfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFpasswordKonfActionPerformed

    private void SIGNUPBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIGNUPBTNActionPerformed
       String username = TFusername.getText();
    String password = TFpassword.getText();
    
    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Username dan Password tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String url = "jdbc:sqlserver://localhost:1433;databaseName=DbNotaku;encrypt=true;trustServerCertificate=true;";
    String userDb = "Test1";
    String passDb = "123"; 

    if (SIGNUPBTN.getText().equals("SIGN-IN")) {
   
        String sql = "SELECT * FROM Pengguna WHERE username = ? AND password = ?";
        
        try (Connection conn = DriverManager.getConnection(url, userDb, passDb);
             PreparedStatement ps = conn.prepareStatement(sql)) {
            
            ps.setString(1, username);
            ps.setString(2, password);
            ResultSet rs = ps.executeQuery();
            
            if (rs.next()) {
    int idUser = rs.getInt("id_user"); 
    JOptionPane.showMessageDialog(this, "Login Berhasil!\nSelamat datang, " + username);
    
    ListNota_1 halamanUtama = new ListNota_1(idUser);
    halamanUtama.setVisible(true);
    this.dispose(); 
}        else {
      
                JOptionPane.showMessageDialog(this, "Username atau Password salah!", "Login Gagal", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Koneksi Gagal: " + e.getMessage());
        }

    } else {
        
      
        String passwordKonf = TFpasswordKonf.getText();
        
        if (!password.equals(passwordKonf)) {
            JOptionPane.showMessageDialog(this, "Password dan Verifikasi Password tidak cocok!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String sql = "INSERT INTO Pengguna (username, password) VALUES (?, ?)";
        
        try (Connection conn = DriverManager.getConnection(url, userDb, passDb);
             PreparedStatement ps = conn.prepareStatement(sql)) {
            
            ps.setString(1, username);
            ps.setString(2, password);
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Akun berhasil dibuat! Silakan masuk menggunakan akun baru Anda.");
            
            ButtonAkunLamaActionPerformed(evt); 
            
        } catch (SQLException e) {
            if (e.getErrorCode() == 2627) { 
                JOptionPane.showMessageDialog(this, "Username '" + username + "' sudah terdaftar. Silakan gunakan username lain!", "Gagal", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Gagal membuat akun: " + e.getMessage());
            }
        }
    }
    }//GEN-LAST:event_SIGNUPBTNActionPerformed

    private void ButtonAkunLamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAkunLamaActionPerformed

    lblpasswordKonf.setVisible(false);
    TFpasswordKonf.setVisible(false);
    
    JudulBuatAkun.setText("LOGIN AKUN");
    SIGNUPBTN.setText("SIGN-IN");
    
    TFusername.setText("");
    TFpassword.setText("");
    TFpasswordKonf.setText("");
    }//GEN-LAST:event_ButtonAkunLamaActionPerformed

    private void ButtonAkunBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAkunBaruActionPerformed
       lblpasswordKonf.setVisible(true);
    TFpasswordKonf.setVisible(true);
    
    JudulBuatAkun.setText("BUAT AKUN");
    SIGNUPBTN.setText("SIGN-UP");
    
    TFusername.setText("");
    TFpassword.setText("");
    TFpasswordKonf.setText("");
    }//GEN-LAST:event_ButtonAkunBaruActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login_0().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton ButtonAkunBaru;
    private javax.swing.JButton ButtonAkunLama;
    private javax.swing.JLabel JudulBuatAkun;
    private javax.swing.JButton SIGNUPBTN;
    private javax.swing.JTextField TFpassword;
    private javax.swing.JTextField TFpasswordKonf;
    private javax.swing.JTextField TFusername;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblpasswordKonf;
    // End of variables declaration//GEN-END:variables
}
